### ISSUE TITLE
Look at # of satellites connected to determine if point is valid.

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#147]
Right now we only look for the LOCK flag and that is throwing some problems with some devices that are connected to 5+ satellites but still not getting a LOCK for some reason, though location is likely fine

**Comment by Frangible** [comment]
This is likely not resolvable due to a bug in bGeigie firmware(s) where the number of satellites is not being correctly reported.

For example, this is from 209-0312.LOG, and is the first line which is invalid, and a later line that is valid.  The number of satellites is identified as being 80 and 94, respectively.  Note that there are only 32 GPS satellites in orbit.

$BNRDD,209,2015-03-12T03:31:47Z,0,0,0,V,3342.7433,N,11206.8081,W,445.40,A,80,10*77
$BNRDD,209,2015-03-12T20:15:56Z,53,6,7789,A,3504.0378,N,11101.9945,W,1663.20,A,94,9*65

**Comment by seanbonner** [comment]
Thanks! I'll add a new issue related to that bug.

**Comment by nokton** [comment]
Hi Nick,

Somewhat related - is height and 5sec CPS being uploaded in the database? Or is this issue covered somewhere else already?

Pieter

**Comment by hkwi** [comment]
Is that log file id 18430 which was written in 1.0.2nano format?

**Comment by Frangible** [comment]
Sort of.  Altitude and cp5s make it into an import table, but altitude is always null when inserted into table measurements and cp5s is ignored entirely.  There aren't any problems with the source data like with numsats though.

**Comment by Frangible** [comment]
That sounds correct.

**Comment by nokton** [comment]
Hi Nick,

Then those 2 are certainly things to be fixed - do they appear in the github bug list?

For numsat, the format differs based on which GPS unit it used. The bGeigie Nano and bGeigie+ use Adafruit modules, which report the number of satellites. Earlier bGeigies use a different unit which gives some other type of indicator (in the same field)

Pieter

**Comment by Frangible** [comment]
No existing bugs I'm aware of prior to this. That's a bGeigie Nano logfile, recent one from Sean's I had grabbed earlier for testing.
