### ISSUE TITLE
Rotate SSL keys for api.safecast.org

### ISSUE THREAD

**Issue by atalax** [Safecast/safecastapi#179]
There is an SSL key in `doc/ssl/safecast.key` which seems to be the one used by http://api.safecast.org. There is also some postgres password in `doc/.pgpass`. This is probably not intentional.

**Comment by Steven-Wright** [comment]
This is indeed the case:
I downloaded the live API cert and compared it against the key, they have the same public exponent and modulus.

```
steven$ echo -n | openssl s_client -connect api.safecast.org:443 > safecast.crt
steven$ openssl rsa -noout -modulus -in safecast.key | openssl md5
d56eeea688ffb168b7d86be1e01b2a72`
steven$ openssl x509 -noout -modulus -in safecast.crt | openssl md5      
d56eeea688ffb168b7d86be1e01b2a72
```
`doc/.pgpass` gets copied into place by `/deploy/after_restart.rb`.

Both of these are pressing security issues. I'm not sure exactly how the app is deployed from the repo but I see two easy ways out. 
1. move `doc` to a local directory on the server and provide a symlink in the repo
2. move `safecast.key` and `.pgpass` to a local directory, ignore them in git, and copy them in with a post-merge hook (this way when you pull the latest stable version it will copy them over)

```
#!/bin/sh
#!/usr/bin/env sh
PRIVATE=~/private
DOC_PATH=$PWD/doc

#copy the ssl directory into place
cp -R $PRIVATE/ssl $DOC_PATH
#copy the pgpass into place
cp $PRIVATE/.pgpass $DOC_PATH
```

I'd imagine that something similar is already happening to handle the files present in `.gitignore`.

**Comment by robouden** [comment]
Working to get the keys removed and made a private repro for the keys.

**Comment by Steven-Wright** [comment]
@robouden - if you are making a private repo perhaps a submodule is the best bet.

**Comment by diffalot** [comment]
I would advise against using a submodule for keys, I think it's better to .gitignore them.

The way submodules track commit hashes, `git submodules update` would throw errors in any environment except production (assuming that only production has access to the keys repo).

**Comment by Steven-Wright** [comment]
@diffalot, then as per your [article](https://diff.mx/2015/01/git-subtree/) maybe git-subtree is more appropriate or maybe it could be as simple as a git stash. As it stands now, how does this repo get deployed?

**Comment by diffalot** [comment]
@Steven-Wright Asking how the repo gets deployed is the right question here.

Personally, I believe that the best security practice is to keep these keys only on the server being deployed to or in backups of those servers.  Keys should never be stored in a repository.  

It's up to the SysAdmin as to how they want to reference these keys during deployment, be it environment variables or files listed in .gitignore.

Because this repo is public, and because the keys are now available to anyone through GitHub, we must, at the least, generate new keys, and we should do a [git filter branch](https://help.github.com/articles/remove-sensitive-data/) on all branches of this repository.  (It's necessary to generate new keys because our old keys will still be cached on GitHub's CDN at commit [specific addresses like this](https://raw.githubusercontent.com/Safecast/safecastapi/cdb44c0b5d134491284e2f7619da807187370b9e/doc/ssl/safecast.key) until GitHub expires that content.

The problem with git filter branch is that it requires pushing back to GitHub with --force because it rewrites the sensitive files out of the repository history, and doing that requires that every developer `pull --force` on their development machines.  It's not particularly dangerous, but it could be frustrating if anyone doesn't get the memo that this is going to happen.

I recommend:

1. Whoever is in charge of deployment and systems administration generate new keys and make sure the site is running on them. After that, there is no great rush to proceed to step 2, because the keys visible on GitHub are no longer a security risk.
2. We pick a date to remove all these keys from the repo, and make sure everyone knows about it.
3. Everyone does a as yet undetermined series of git commands (first, backup local repos, then git fetch all --force with pruning or something, followed by rebasing their current working branches onto the cleaned branches they forked from).

**Comment by Steven-Wright** [comment]
@diffalot - I think we are on the same page. Best practices mandate new keys and a purge of the repo, although care must be taken to also have this extended onto all forks and their branches. These keys still pose a security risk as SSL key revocation isn't always reliable.

If we can gather more information on the deployment of the code to the production environment then we can decide what the most appropriate way to keep this information out of the repo with as little additional complexity added to the development and production environment as possible.

**Comment by diffalot** [comment]
Fully agreed, @Steven-Wright.  I'm afraid my attitude may have come across as cold, rather than 'keeping cool in dealing with security concerns'

I'm sorry.

As I'm hardly a Ruby coder, I got a little overexcited about being able, at long last, to contribute.

**Comment by Steven-Wright** [comment]
@diffalot, I wasn't bothered. I saw that you had identified this as a potential issue in the wiki on Jun 5, 2013. That's follow through.

**Comment by diffalot** [comment]
Phew.

I'm happy to stay on standby in slack to help people with git troubleshooting, when the purge is happening.

**Comment by diffalot** [comment]
some good news: it looks like there are only two public repos with this key: 

https://github.com/search?q=MIIEpAIBAAKCAQEAvhrcgwXqD64jOWp4PV9exc%2BNvlE%2BbPc1RGxNoxm8jqLUZlsF&ref=reposearch&type=Code&utf8=%E2%9C%93

and, GitHub Support can be contacted to clear their cache after we filter the branches.

**Comment by matschaffer** [comment]
I removed the pgpass, but I'm going to hold on doing any filtering.

Looks like we have 20 unmerged branches right now and filtering master will require some rework of each of those.

Once we have all secrets removed from the repo we can do a flag day where everything gets new shas.

**Comment by matschaffer** [comment]
Got a recommendation to use https://www.cloudflare.com/ssl/ since they have a free SSL offering that will allow us to use a self-signed cert between cloudflare and origin.

Letsencrypt would also be interesting but we would first want to verify if the support is similar to our browser footprint.

**Comment by matschaffer** [comment]
AWS move is looking likely, at which point we can use the AWS-provided certs for this.

**Comment by matschaffer** [comment]
We have an ACM cert for AWS assets at this point. Closing since it will make more sense to finish that move rather than re-issuing the current cert on c66.

**Comment by matschaffer** [comment]
New LB is in place handling SSL termination via letencrypt (still cloud66+digitalocean).

And once we finish the move to AWS it'll be ACM which is already provisioned and being used for ingest.safecast.org.
