### ISSUE TITLE
Safecast Drive iOS app unable to authenticate when using `ja` locale

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#325]
From Heiwa:

I found out the cause of this trouble.  I have changed time zone and default locale in my profile, then i can sign in with my first id!!
Because i need to explain how to use api for my Japanese friends who cannot understand English, I have edited my profile.  That's triggered this trouble."

**Comment by eitoball** [comment]
I cannot understand what the problem is... 😢 So,

1. What is the procedure to reproduce this issue?
1. What result was gotten?
1. What is expected result?

I understand that this person

1. changed her/his timezone and default locale
1. got message; "You are already signed in."

Did she/he try to access sign-in (/users/sign-in) page after editing profile? If so, she/he needs to sign out first.

**Comment by robouden** [comment]
The IOS APP have same message when trying to upload the data "You are already signed in"..

**Comment by eitoball** [comment]
Oh, is this issue basically same as issue Pieter described in [here](https://safecast.slack.com/archives/api/p1468327016001544) ?

**Comment by robouden** [comment]
yes



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> twitter:robouden <http://bit.ly/RAiSTC>

**Comment by eitoball** [comment]
@robouden Do you know which is correct repository for Drivecast for iOS, https://github.com/mcrollin/Drivecast or https://github.com/Safecast/Drive-ios ? `Info.plist` files in both repo don't have '1.1' string... 

The reason I am asking is that there is a function; `SDCSafecastAPI.signInUser`. This function is called when user tries to sign in. This function in one repo (mcrollin/Drivecast) calls `SDCSafecastAPIRouter.SignOut`, and the same function in other repo does not.

This issue seems that the app makes sign in request with cookie that contains authentication information. If app calls sign out request before, there should not be authentication info in cookie.

**Comment by robouden** [comment]
The https://github.com/Safecast/Drive-ios should be the "official one"..https://github.com/mcrollin/Drivecast  is Marc's one.  Could you compile both and test which one works?

**Comment by eitoball** [comment]
In short, you should not change your locale to 'ja' if you use Drivecast for iOS.

### How to reprocedce

(As in description of this issue)
1. Change your locale to 'ja'
2. Sign out from app if you are signed in
3. Sign in

### Why?

The reason of this failure is that the app is looking for string "(Retrieve your API key)" on dashboard page after signing in. If your locale is "ja", the app cannot find the string because it is translated, and app return an error (https://github.com/Safecast/Drive-ios/blob/master/Drivecast/Libraries/SDCSafecastAPI.swift#L199-L212).

### Solution

There are several solutions

1. Modify safecastapi to be able to sign in with JSON, and modify app to authenticate with JSON.
1. Modify safecastapi to become OAuth2 provider, and modify app to authenticate in OAuth2.
1. Modify safecastapi to force locate to 'en-US' if access is from iOS app.

I would like OAuth2 solution, but it takes time. JSON solution is feasible. Forcing locale solution needs to modify only safecastapi, but really ugly and not recommended.

**Comment by eitoball** [comment]
Drivecast for iOS always uses 'en-US' locale when it submit requests to api even user's locale is 'ja. This might not be related, but it seems to cause different error.

**Comment by matschaffer** [comment]
The notion of a JSON-based auth API is covered in https://github.com/Safecast/safecastapi/issues/218 so this might be closable (or re-openable as a bug on the iOS app. Thoughts @eitoball ?

**Comment by eitoball** [comment]
Will provide API; `GET /users/me.json`
