### ISSUE TITLE
Reminder for pending submissions

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#431]
As noted on https://api.safecast.org/en-US/bgeigie_imports?by_status=processed&order=created_at+desc we have a growing number of uploads that haven't been given metadata or submitted for review.

Would be good to start reminding people. Maybe a weekly status email.

**Comment by seanbonner** [comment]
Yes, we need to get these drives actually submitted, so it would be ideal for people to get an email every week after they upload a log reminding them that the need to actually go in and submit it to us, and until they do that they haven’t actually contributed the data but are using Safecast resources. I think it’s OK to point that out here, as people often don’t realize that uploading isn’t submitting, and that we actually pay to host the data.

Would be great if people got an email for each log that they’ve uploaded but not submitted, with a link to it and a nudge to go in and add the metadata and submit it.

On February 20, 2018 at 10:50:16 AM, Mat Schaffer (notifications@github.com) wrote:

As noted on https://api.safecast.org/en-US/bgeigie_imports?by_status=processed&order=created_at+desc we have a growing number of uploads that haven't been given metadata or submitted for review.

Would be good to start reminding people. Maybe a weekly status email.

**Comment by matschaffer** [comment]
Maybe for another gh issue, but keeping an eye on the number of drives in given states over time would probably be good too. Mentioning it here incase we see an easy path to it while working on the reminder email.

**Comment by Lugulbanda** [comment]
I think the problem is build in, cuz most people only walk around using the app on the phone ,
most of them don't know they have to access the api side to finish it, for them its upload and forget..
and the api page for handys is not very nice its way to tiny....

spoken from my side as i struggled on this page in the beginning, its also not easy to understand were u have to go, to do what, if ur new, cuz on the api is no help link how to do it step by step.
i worked it out for myself but it was "NOT EASY" but it should be.

there are lots of links which lead u somewhere but not directly to ur upload, wich need to be modified, the mainpage could be reworked, so u first see what u need not whats all possible.

actually for a first time user the side offers to much misleading links and no straight way ....

there should be a first time page if u create ur account with the retrieve api key , wich u later never will see again until u click the link to it..

after the creation and login it should directly lead to 
https://api.safecast.org/en-US/bgeigie_imports?by_status=processed&by_user_id=xxxx

or if no uploads in the system https://api.safecast.org/en-US/bgeigie_imports/new

there should be a little help page which shows the people, were to click and were to enter what, 
the actual page is ok, for people who grow up with safecast bit by bit, 

but for beginners and handy users, without much knowledge of computers, and how the hole system works, it needs some guidance, to make it easy for them...

also i miss a forum a chat room were beginners, can ask questions to get helped from others, 
Safecast is a great projekt, but somehow it excludes the communication under the users completely, its nice to see someone next to me is doing measurements, but... i cant contact to him why?
Why there is no platform were users help users and share their experience in the daily measurement work. sometimes i see safecast as a great tool, and what many can achieve, but with a big brake on, cuz ignoring the power of the people helping themself...

i can only speak for me a foreigner, which had no guide, no help, no workshop,  

iam absolutely sure if there had been such a platform, which should easier to find then as example lead to Slack only to get the message slack is only for inventors and programmers to share stuff...

i don't want to step on ur feet, but sometimes if u do a thing over a long time u loose the sight for the small problems, which can be Mountains for People which are not so deep in...

the app does it great, but struggles in the finishing line, cuz its relenting on the weppageapiside, wich is not written for mobile use, and not easy to understand api page if ur new...
spoken for me i don't use the app in this final case cuz its so tiny so boring to do it there... i wait until i'm home on my 27" Monitor to work on it.

just my 2 Cents...

**Comment by matschaffer** [comment]
Yeah slack is a great platform for chat, but pretty terrible for community bulding. So we tend to rely on the device owners mailing list. 

Not sure what the right answer is there. Discourse comes to mind but it'd take time for folks used to slack to get any new tool into their workflow. 

And the UX is also a fairly well known problem we'd love to.have someone to help work on. Definitely some good ideas here. I'd welcome any code changes you'd be comfortable submitting.

**Comment by matschaffer** [comment]
Bumping to next given @nokton's [request in slack](https://safecast.slack.com/archives/C026F2Q1U/p1527643203000156)

**Comment by seanbonner** [comment]
Let's get this back into motion, I think the conversation in slack is just continued frustration that this keeps piling up, so let's try to get this done and shipped and then we can fine tune later. It's a problem that gets worse every single day, so better to have some solution in place than nothing.

**Comment by matschaffer** [comment]
![Screen Shot 2019-09-13 at 11.12.25 PM.png](https://images.zenhubusercontent.com/579ea40fe40e5714b16cbfe1/4561c4e6-6d63-4f98-a7c2-716312a7a981)

Hey it worked :)

**Comment by matschaffer** [comment]
webhook check

**Comment by matschaffer** [comment]
another webhook check

**Comment by matschaffer** [comment]
and again

**Comment by matschaffer** [comment]
one more

**Comment by matschaffer** [comment]
maybe now?

**Comment by matschaffer** [comment]
ah ah ah
