### ISSUE TITLE
Add URL aliases for easier uploading

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#49]
Realizing that api.safecast.org is confusing for people so we should set up submit.safecast.org & upload.safecast.org that direct right to the upload pages...

**Comment by thinrope** [comment]
@seanbonner : to upload data, one needs account anyway and adding more domains might get us to a worse situation. Currently API is both upload, some vizualization, admin and download... data.safecast.org may be used once we have better ways to show data (to download), since we'll have many more downloads than uploads. Then upload button is UI issue (again, you'll need account, so Login button should also work)

@nokton: it is probably quite a different issue, since current api does not have graphical endpoint for non-drive data:
drive example: https://api.safecast.org/en-US/bgeigie_imports/16956
nGeigie example: https://api.safecast.org/en-US/devices/100022/measurements

**Comment by matschaffer** [comment]
Is this from people being told to go to a certain url in the workshop?

We can certainly add redirect URLs, but I wonder if having some clear button/link on safecast.org (currently blog.safecast.org) might be a better move.

**Comment by nokton** [comment]
Would vote to close this as new blog will have all pointers into whereever.

**Comment by matschaffer** [comment]
Seconded
