### ISSUE TITLE
Add updated_at index to measurements table

### ISSUE THREAD

**Issue by sasharevzin** [Safecast/safecastapi#666]
I was digging around and found that slowest requests are on `MeasurementsController#index` and it happens when someone is trying to fetch the list of Measurements using `since` filter like [/measurements.json](http://api.safecast.org/measurements.json?per_page=1000&since=2020-05-05%2B01%3A15%3A03)

[NewRelic](https://rpm.newrelic.com/accounts/1057812/applications/10580222/datastores#/overview/Postgres/trace/?id=a6b6e952-8e6c-11ea-a7a1-0242ac110007_0_3127&metric=Datastore%252Fstatement%252FPostgres%252FMeasurement%252Ffind) and [Kibana](https://5bc3d4f7330a4459881197a85659caf5.us-west-2.aws.found.io:9243/app/apm#/services/safecastapi-prd/transactions/view?rangeFrom=now-24h&rangeTo=now&refreshPaused=true&refreshInterval=0&traceId=994b74af1b48a758592db089a9ef6f38&transactionId=6c30783bca3d6dd4&transactionName=MeasurementsController%23index&transactionType=request&detailTab=metadata)

Proposed solution is to add an index on `updated_at` OR add another field that will contain only `date` to reduce an index size that won't include time (who care about, right?)

PS. I know, this is a pretty huge table and adding another index might overkill but table has index on `captured_at` so maybe it's ok?

**Comment by matschaffer** [comment]
Yeah, that's https://realtime.safecast.org/ doing that

I'm _fairly_ certain the indices required are all in place, but the app has a couple of problems. One is that it queries a few hundred sensors in a loop (2 req per sensor) and the other is it's just a cron, and sometimes it starts overlapping itself. (looks like it's not at the moment, so that's good).

https://github.com/Safecast/safecastapi/issues/606 is our overall plan to fix that. If we can have api handle the same sort of device status/story work that https://realtime.safecast.org/ does, we can shut it down and stop the wasteful polling it does today.

**Comment by matschaffer** [comment]
oh whoops, now that I look more closely, your'e calling out something else. Pretty sure that's https://github.com/radoondas/safecastbeat which I could have _sworn_ I had an index on `updated_at` for

But doesn't seem to be one now. Game on on creating one.
