### ISSUE TITLE
Some of measurements have incorrect date

### ISSUE THREAD

**Issue by sasharevzin** [Safecast/safecastapi#674]
https://api.safecast.org/en-US/measurements?locale=en-US&order=captured_at+asc

I assume that log had `yy` instead of `yyyy`

<img width="732" alt="Measurements____Safecast_API" src="https://user-images.githubusercontent.com/232392/81195910-691e2c80-8f8c-11ea-8a39-5e01bf390fbd.png">

**Comment by eitoball** [comment]
These data seems to be from https://api.safecast.org/en-US/measurements/new (Don't click due to #730) because there are no associated bGeigie imports. In this "Contribute your Measurement" form, you can enter dates freely, `captured_at` were entered like `19-11-02`. I checked database, measurement (id: `145127129`) were created on 2019-08-23. At least, measurements in description are such data.

There are some measurements like https://api.safecast.org/en-US/measurements/15768509 and https://api.safecast.org/en-US/measurements/1582113 that have assosicated measurement import ids. But, there are no bGeigie imports with those IDs. Should those measurements be deleted?

And, some measurements submitted by [Quara-Radex](https://api.safecast.org/en-US/users/345) have captured data like 1969/12/31 and 1970/01/05. There are no associated measurement imports. They seem to be submitted via API with wrong `captured_at`.
