### ISSUE TITLE
New device story display is affecting CSS of "Devices" tab in nav bar

### ISSUE THREAD

**Issue by auspicacious** [Safecast/safecastapi#684]
The device story display accepted in PR #680 is changing the color of this link (thanks @matschaffer for the screenshot)
<img width="420" alt="Add_basic_display_to_device_story__Ref__606_by_sasharevzin_·_Pull_Request__680_·_Safecast_safecastapi" src="https://user-images.githubusercontent.com/11050776/82667100-22118600-9c72-11ea-9b0b-e39d7d8ec2b2.png">

**Comment by sasharevzin** [comment]
What she’ll we do here? Rename it and update the url it add a new like to stories?

**Comment by matschaffer** [comment]
Let's add a new "Device Stories" link there.

I know we're all not super excited about the name, but it's what we have for now.

Secondarily, I'd be fine (maybe even prefer) just having the controller named that way instead of the current "DeviceStory::Device" setup we have right now. Mentioning this incase it makes the ccs easier by renaming the controller.

I'll try to find some time to write up more about what I'm imagining for all this and why I still feel like it's a decent name.

But for starters, I think it's important to call out that what we're building is basically a "join model" between a person and their hardware. It's the relationship between a person and a machine we're trying to capture here.

**Comment by sasharevzin** [comment]
Thanks, @matschaffer. What is the preferable name for the model? `DeviceStoryDevice`? Weird, right? Do you think I can a migration to rename the table to `device_stories` so we can have the `DeviceStory` model?

**Comment by matschaffer** [comment]
I think we should, yes.

**Comment by sasharevzin** [comment]
Thanks. I'll prepare a new PR. 
CCed @eitoball

**Comment by sasharevzin** [comment]
Here is a new PR:
https://github.com/Safecast/safecastapi/pull/687
@matschaffer @auspicacious @eitoball
